### ISSUE TITLE
파이프라인 리팩토링

### ISSUE THREAD

**Issue by mizuirohoshi7** [wanted-preonboarding-team-m/02_geoRecommendEats#10]
## 📝 Description

파이프라인 관련 코드를 리팩토링 혹은 버그 픽스합니다.

## ☑️ TODO

- [x] 맛집 테이블과 속성 테이블을 1:N 관계에서 1:1 관계로 수정
- [x] ddl-auto를 update로 해도 매번 몇분씩 걸리는지 확인
- [x] csv onApplicationEvent 파라미터 수정
- [x] 패키지 위치 수정
