### ISSUE TITLE
데이터 파이프라인 구축

### ISSUE THREAD

**Issue by jhva** [wanted-preonboarding-team-m/02_geoRecommendEats#4]
## 📝 Description
- OpenAPI 로 부터 데이터를 JSON 형태로 요청 
   -  요청 받은 데이터로 dto 생성
## ☑️ TODO
- [x] OpenAPI로 부터 데이터를 `RestTemplate`을 통해 JSON 형태로 받아온다
- [x] 받아온 데이터를 전처리하여 값이 null인 속성은 default 값을 지정해준다.
- [x] Restaurant 관련 엔티티 및 리포지토리 생성
- [x] 리포지토리를 이용하여 전처리된 값들로 엔티티를 생성하고 저장한다.

@mizuirohoshi7
